### ISSUE TITLE
Cassandra is working no different port

### ISSUE THREAD

**Issue by zachys** [jeffjirsa/bottle-cassandra-driver#1]
Is it possible to change the driver's connection port to Cassandra from the default 9042?
I have my Cassandra working on a non-default port due to firewall issues.

**Comment by jeffjirsa** [comment]
The datastax driver allows alternate ports - pushed up  rev 0c04a36 to expose port (as well as compression, load balancing policy, etc).

**Comment by jeffjirsa** [comment]
Where previously you'd have used:

```
cql_plugin = bottle_cassandra_driver.CassandraPlugin(endpoints=['127.0.0.1'], keyspace='example')
```

Now:

```
cql_plugin = bottle_cassandra_driver.CassandraPlugin(endpoints=['127.0.0.1'], keyspace='example', load_balancing_policy=DCAwareRoundRobinPolicy(local_dc='US_EAST'), port=9999 )
```

**Comment by zachys** [comment]
You'r prompt help is very appreciated! Thank you
